FROM ubuntu:20.04
RUN apt-get update -y
RUN apt-get install apache2 -y
RUN apt install libapache2-mod-php php-mysql -y
RUN mkdir /var/www/app/
WORKDIR /var/www/app
COPY ./ ./
RUN chown www-data:www-data -R /var/www/app/
COPY ./php.conf /etc/apache2/sites-available/
RUN echo "ServerName localhost" >> /etc/apache2/apache2.conf
RUN a2enmod rewrite 
RUN a2dissite 000-default 
RUN a2ensite php.conf 
RUN service apache2 restart
EXPOSE 80
ENTRYPOINT [ "apache2-foreground" ]